name: Build

on:
  push:
    branches:
      - master  # Adjust this to match the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to the version you need for your project

      - name: Install dependencies
        run: npm install

      - name: Build with esbuild
        run: npm run build  # This runs the "build" script from your package.json
