name: Build and Create Pull Request
on:
  push:
    branches:
      - master  
jobs:
  build_and_pr:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust this version according to your project's requirement
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  

    - name: Commit and push the 'dist' folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f dist
        git commit -m "Update 'dist' folder"
        git push origin master

